# SPDX-FileCopyrightText: 2019 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
coverage:
  range: 50..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 2%
        paths:
          - "github.com/xmidt-org/wrp-listener/..."
    patch:
      default:
        target: auto
        threshold: 2%
        paths:
          - "github.com/xmidt-org/wrp-listener/..."
    changes:
      default:
        target: auto
        threshold: 2%
        paths:
          - "github.com/xmidt-org/wrp-listener/..."

ignore:
  - "*_test.go"
  - "vendor"

fixes:
  - "github.com/xmidt-org/wrp-listener/::"
